# Generated by Django 3.1 on 2020-08-16 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pannah', '0002_customer_gender'),
        ('pannah', '0002_volunteer'),
    ]

    operations = [
    ]
