# Generated by Django 3.1 on 2020-08-16 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pannah', '0003_merge_20200816_1140'),
        ('pannah', '0004_scheme'),
    ]

    operations = [
    ]
